# Basic Python

## 1. Split This String

In [ ]:
s = "Hi there sam!

In [2]:
s = "Hi there sam!"
x=s.split()
print(x)

['Hi', 'there', 'sam!']


## 2.Use .format() to print the following string

### Output should be: The diameter of earth is 12742 kilometers

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
planet = "Earth"
diameter = "12742"
print("The diameter of {} is {} kilometers" .format(planet,diameter))

The diameter of Earth is 12742 kilometers


### 3.In this nest dictionary grab the word "hello"

In [ ]:
{'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [ ]:
import numpy as np

## 4.1 Creat an array of 10 zeros?

In [6]:
import numpy as np
array=np.zeros(10)
print("An array of two zeros:")
print(array)

An array of two zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 4.2 Create an array of 10 fives?

In [7]:
import numpy as np
array=np.ones(10)*5
print("An array of ten fives:")
print(array)

An array of ten fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5.Create an array of all the even integer from 20 to 35

In [8]:
np.arange(20,35,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6.Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7.Concatenate a and b 
## a = np.array([1,2,3]),b = np.array([4,5,6])

In [11]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8.Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd

In [13]:
import pandas as pd
temp = {"project_num":["No.1","No.2","No.3",],"status":["Doing","Done","Ready"]}
pd.DataFrame(temp)

project_num status
0        No.1  Doing
1        No.2   Done
2        No.3  Ready

## 9.Generate the series of datas from 1st jan, 2023 to 10th feb 2023

In [14]:
pd.date_range(start="2023-01-01",end="2023-02-03")

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03'],
              dtype='datetime64[ns]', freq='D')

## 10.Create 2D list to Data Frame

### lists = [[1,'aaa',22],[2,'bbb',25],[3.'ccc',24]]

In [15]:
lists = [[1,'aaa',22], [2,'bbb',25], [3,'ccc',24]]
ds=pd.DataFrame(lists)
print(ds)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
